### ISSUE TITLE
[Feature Request] Adding support for dataview inline keys as pageLink

### ISSUE THREAD

**Issue by dummifiedme** [HEmile/juggl#102]
Currently, juggl supports the feature to have markings on the graph based on the word before the link such that `- hasPainted [[a painting]]`.

My general use case to have a formulated dataview list and breadcrumb both is to have a simple inline dataview field, `Painted:: [[A Painting]]`. This way if I have to reference all the paintings by respective painters, I can have it and at the same time it will show up on Breadcrumb child as well if I have it there in my Heirarchies.

I was wondering if juggl can pickup these things as well. If a file is linked via a field, it shows up on the graph with the link named after the field. `[[A painter]] — Painted —> [[a Painting]]`

**Comment by HEmile** [comment]
The next Breadcrumbs release will integrate with Juggl and will also work with any BC syntax (including this one). I'll leave this issue open though as a general issue as this is a common typed link format.

**Comment by HEmile** [comment]
This will be supported in the next Breadcrumbs release, when Breadcrumbs, Dataview and Juggl are all active.
