### ISSUE TITLE
Juggle view on top of the note not showing

### ISSUE THREAD

**Issue by adeldaoud** [HEmile/juggl#117]
For some reason, the juggle view on top of the note not showing, despite that I have activated it. Any ideas why?

![image](https://user-images.githubusercontent.com/9431362/153731552-53926dca-d2e3-481c-91ba-2f1f47007ab1.png)

**Comment by adeldaoud** [comment]
I just realized that I did not have the most recent Juggle update and I have updated the package. So now the graph is showing, but I wonder how I can reduce clutter in the shown graph? E.g., how can I remove the bi-directional arrows, and just rely on Breadcrumb's hierarchies? Thanks

![image](https://user-images.githubusercontent.com/9431362/153731821-46270e6b-8f85-4831-b9ce-e843814405ef.png)

**Comment by HEmile** [comment]
Good to hear it's showing! This issue will be resolved in one of the next Breadcrumbs updates.

**Comment by adeldaoud** [comment]
ok, great to hear that! Feel free to close this comment or leave it open as a mental note.
