### ISSUE TITLE
Add more than one direction in codeblock

### ISSUE THREAD

**Issue by adeldaoud** [HEmile/juggl#118]
The code examples for codeblock shows how to add one direction "dir". But I wonder how to add several directions in the same view. I tried variants of the following code but that did not work. Any ideas?

```

```breadcrumbs
type: juggl 
dir: {next, down}
layout: force-diracted
fdgdLayout: d3-force
depth: 0
navigator: true
```

```

**Comment by HEmile** [comment]
This is an issue for the Breadcrumbs plugin, so I'll close it in this repo. Feel free to reopen it there.
