### ISSUE TITLE
feature request: Outline view of Graph

### ISSUE THREAD

**Issue by classicrob** [HEmile/juggl#121]
Similar to the hierarchical graph view, I would love to be able to see the graph as a bulleted outline that I can collapse / expand.

**Comment by HEmile** [comment]
Similar to how Breadcrumbs has a down view? That's likely a won't do for this plugin, it does not really fit with the design of the graph view and is not supported by the library i use

**Comment by classicrob** [comment]
Not quite... Thinking about something like this. All linked nodes can just be indented underneath the given node.
![CleanShot 2022-02-25 at 16 30 45](https://user-images.githubusercontent.com/46608303/155820707-d85cc78e-e7f9-4968-b672-20b520b3841c.png)

**Comment by HEmile** [comment]
Yes, that's what i meant. I don't think this fits the design of juggl at all, and would work better as a separate plugin. Also, trees cannot fully represent graphs like this.
