### ISSUE TITLE
I used graph query language when there was a neo4j

### ISSUE THREAD

**Issue by DmitryKorzhov** [HEmile/juggl#132]
Good afternoon, I was using Cypher quering when you had Neo4j. Now, as I understand it, there is no such thing.

Please tell me why you closed Neo4j project? And how you can use queries to the graph now?

**Comment by HEmile** [comment]
I didn't end up using that feature much, right now I mostly query using the Breadcrumbs plugin. If you want to use CYPHER with Obsidian, your best guess is to try out the deprecated/ dead plugin Neo4j stream, which you have to install from source: https://github.com/HEmile/obsidian-neo4j-stream
