### ISSUE TITLE
Broken documentation link in the settings menu

### ISSUE THREAD

**Issue by Jaalte** [HEmile/juggl#44]
It links to [https://publish.obsidian.md/semantic-obsidian/Neo4j+Graph+View+Plugin](https://publish.obsidian.md/semantic-obsidian/Neo4j+Graph+View+Plugin), which is dead

You should replace it with [https://juggl.io/Neo4j+Graph+View/Neo4j+Graph+View+Plugin](https://juggl.io/Neo4j+Graph+View/Neo4j+Graph+View+Plugin), which works

[Here's where it is in settings.ts](https://github.com/HEmile/obsidian-neo4j-graph-view/blob/c99c4854acb00b0664f5dddb195539ffe9c104e0/neo4j-graph-view/settings.ts#L92)

**Comment by Jaalte** [comment]
I'll try to add it to https://github.com/HEmile/semantic-obsidian/tree/main/Semantic%20Obsidian

**Comment by HEmile** [comment]
Thanks for the report! I fixed this to the correct link.
