### ISSUE TITLE
Properly close down Juggl panes on unload

### ISSUE THREAD

**Issue by HEmile** [HEmile/juggl#48]
When Obsidian unloads, the style panes do not properly close down and don't load on Obsidian start. 
Check out how the calendar plugin handles this.

**Comment by Mpic** [comment]
I suppose that's why Juggl opens 2 empty panels at the top right when Obsidian starts ?

![2 empty panels opened at launch](https://user-images.githubusercontent.com/5664276/115046363-a9de2f80-9ed7-11eb-8b19-ad11c4d3e19c.png)

**Comment by HEmile** [comment]
Yep! Will fix it in the next release. Apologies!
