### ISSUE TITLE
Sidebar panes added repeatedly

### ISSUE THREAD

**Issue by OliverBalfour** [HEmile/juggl#50]
First things first, this is an awesome plugin, thanks for making this!

I've just got one issue: When Juggl is enabled, I get two extra right sidebar tabs for nodes and style. When I close Obsidian and reopen it, these two tabs become blank "No file is open" tabs, and two new nodes and style tabs appear. This means when opening/closing Obsidian a number of times, I end up with dozens of blank sidebar panels.

Here's an example after reopening Obsidian twice:

![image](https://user-images.githubusercontent.com/11626018/115135107-116fb880-a059-11eb-95ef-a0102a0a07d7.png)

After a few days it becomes tricky to use the right sidebar, as you can't scroll the tab view.

I think the old tabs should be re-used instead of becoming blank. Also, if the nodes and style tabs aren't there, I don't think Juggl should bring them up automatically - I personally don't use them, and would prefer they were hidden. Alternately, having an option to stop them automatically appearing would be nice.

**Comment by HEmile** [comment]
Hi Oliver! This should have been fixed in v1.0.5 . Have you updated recently?

**Comment by OliverBalfour** [comment]
@HEmile yes you're right, looks like my version is a couple days old 😂

The new version works like a charm. Thanks!
